// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtgC6WOXSMw7YOTPXUtw3cPNSCiIRxgf4',
    appId: '1:940690593956:android:2538d27dc9b3a7e32cae31',
    messagingSenderId: '940690593956',
    projectId: 'habittracker-42d9c',
    storageBucket: 'habittracker-42d9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRUvSvjywvkrIuF3GIUCmYiNJ-OPOqQQ',
    appId: '1:940690593956:ios:b02650c6f54e73722cae31',
    messagingSenderId: '940690593956',
    projectId: 'habittracker-42d9c',
    storageBucket: 'habittracker-42d9c.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATRUvSvjywvkrIuF3GIUCmYiNJ-OPOqQQ',
    appId: '1:940690593956:ios:b02650c6f54e73722cae31',
    messagingSenderId: '940690593956',
    projectId: 'habittracker-42d9c',
    storageBucket: 'habittracker-42d9c.appspot.com',
    iosBundleId: 'com.pavlenko.Habo',
  );
}
